# Generated by Django 3.0.3 on 2020-03-03 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('better_than_github', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='description',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
