# Generated by Django 3.0.4 on 2020-03-07 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('better_than_github', '0002_milestone_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='creator',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
