# Generated by Django 3.0.3 on 2020-03-11 15:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('better_than_github', '0003_issue_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='open_date_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
