# Generated by Django 3.0.3 on 2020-03-10 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('better_than_github', '0004_milestone_closed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='milestone',
            name='closed',
        ),
    ]
