# Generated by Django 3.0.3 on 2020-03-12 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('better_than_github', '0005_remove_milestone_closed'),
        ('better_than_github', '0004_issue_open_date_time'),
    ]

    operations = [
    ]
