# Generated by Django 3.0.3 on 2020-03-12 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('better_than_github', '0006_merge_20200312_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentchange',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
    ]
