# Generated by Django 3.0.3 on 2020-03-24 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('better_than_github', '0009_labelchange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsibilitychange',
            name='description',
            field=models.CharField(default='', max_length=50),
        ),
    ]
