# Generated by Django 3.0.3 on 2020-04-01 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('better_than_github', '0010_auto_20200324_1820'),
        ('better_than_github', '0011_milestonechange_description_title'),
    ]

    operations = [
    ]
